name: Publish Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: gitconfig
        run: |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"

      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm install
      - name: Create .env with github secrets and run script
        run: |
          touch .env
          echo GITHUB_TOKEN=$GITHUB_TOKEN >> .env
          echo NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN >> .env
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
